author_name         = "amelie"
main_dir            = "../"
secret_path         = "../secret.ini"
private_key_path    = "../ssh_key.pem"
region              = "us-east-2"
ec2_avail_zone      = "us-east-2a"