DROP TABLE IF EXISTS account CASCADE;
CREATE TABLE IF NOT EXISTS account(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  creation_date DATE NULL,
  discount REAL NOT NULL,
  type VARCHAR(255) NULL
);

/*
DROP TABLE IF EXISTS user CASCADE;
CREATE TABLE IF NOT EXISTS user(
  id INTEGER PRIMARY KEY AUTO_INCREMENT
);
*/